# Generated by Django 4.0.1 on 2022-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLiga',
            fields=[
                ('posicion_tabla', models.AutoField(primary_key=True, serialize=False, verbose_name='Posicion Tabla')),
                ('fecha', models.IntegerField(blank=True, null=True, verbose_name='Fecha')),
                ('equipo_local', models.CharField(max_length=25, verbose_name='Equipo Local')),
                ('goles_local', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles Local')),
                ('goles_visitante', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles Visitante')),
                ('equipo_visitante', models.CharField(max_length=25, verbose_name='Equipo Visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=15, verbose_name='Nombre Equipo')),
                ('puntos_equipo', models.IntegerField(default=0, verbose_name='Puntos')),
                ('goles_favor', models.IntegerField(default=0, verbose_name='Goles a Favor')),
                ('goles_contra', models.IntegerField(default=0, verbose_name='Goles en Contra')),
            ],
        ),
        migrations.CreateModel(
            name='EquiposLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=25, verbose_name='Nombre Equipo')),
                ('puntos_equipo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntos')),
                ('goles_favor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles a Favor')),
                ('goles_contra', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles en Contra')),
                ('partidos_jugados', models.IntegerField(blank=True, default=0, null=True, verbose_name='Partidos Jugados')),
                ('partidos_ganados', models.IntegerField(blank=True, default=0, null=True, verbose_name='Partidos Ganados')),
                ('partidos_empatados', models.IntegerField(blank=True, default=0, null=True, verbose_name='Partido Empatados')),
                ('partidos_perdidos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Partidos Perdidos')),
                ('en_uso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('UR', 'Uruguay'), ('PE', 'Peru'), ('CO', 'Colombia'), ('PA', 'Paraguay'), ('CH', 'Chile'), ('EC', 'Ecuador'), ('BO', 'Bolivia'), ('VE', 'Venezuela')], max_length=15, verbose_name='Pais')),
                ('valoracion', models.IntegerField(verbose_name='Valoracion')),
                ('posicion', models.CharField(blank=True, choices=[('Arquero', 'Arquero'), ('Defensor', 'Defensor'), ('Mediocampista', 'Mediocampista'), ('Delantero', 'Delantero')], max_length=15, null=True, verbose_name='Posicion')),
                ('goles', models.IntegerField(default=0, verbose_name='Goles')),
            ],
        ),
        migrations.CreateModel(
            name='PlantelPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('velocidad', models.IntegerField(verbose_name='Velocidad')),
                ('regate', models.IntegerField(verbose_name='Regate')),
                ('pase', models.IntegerField(verbose_name='Pase')),
                ('tiro', models.IntegerField(verbose_name='Tiro')),
                ('defensa', models.IntegerField(verbose_name='Defensa')),
                ('fisico', models.IntegerField(verbose_name='Fisico')),
                ('valoracion', models.IntegerField(verbose_name='Valoracion')),
                ('posicion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Posicion')),
                ('goles', models.IntegerField(default=0, verbose_name='Goles')),
                ('pais', models.CharField(max_length=15, verbose_name='Pais')),
            ],
        ),
    ]
