# Generated by Django 4.0.1 on 2022-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futbalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioliga',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equiposliga',
            name='en_uso',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
