# Generated by Django 4.0.1 on 2022-04-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futbalapp', '0002_calendarioliga_slug_alter_equiposliga_en_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarioliga',
            name='slug',
        ),
    ]
