# Generated by Django 4.0.1 on 2022-05-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futbalapp', '0003_remove_calendarioliga_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantelPropio',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='defensa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defensa'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='fisico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fisico'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='pase',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pase'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='regate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Regate'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='tiro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiro'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='velocidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='valoracion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valoracion'),
        ),
    ]
